env: prod
component: shipping
params: "CART_ENDPOINT:prod.shipping.cart_endpoint,DB_HOST:prod.rds.endpoint"

schemaLoadJob:
  create: true
  type: mysql



#  Environment=CART_ENDPOINT={{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.cart_endpoint', region='us-east-1')}}
#  Environment=DB_HOST={{ lookup('amazon.aws.aws_ssm', '{{env}}.rds.endpoint', region='us-east-1')}}